package token;

public enum TokenType {
    // Keywords
    SET, READ, WRITE, APPEND, FOR, ENDFOR, SPLIT, BY, IF, ENDIF,
    FROM, TO, AS, DO, MATCHES, PRINT,
    TRIM, UPPERCASE, LOWERCASE, SUBSTRING, SORT, LENGTH,THEN,
    IN, EQUALS, NOT, ELSE, COMMA, REVERSE, SLEEP,

    // Symbols
    // PLUS, MINUS, ASTERISK, CARET,
    OPERATOR,
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACKET, RIGHT_BRACKET,

    // Identifiers and literals
    IDENTIFIER, STRING_LITERAL, NUMBER_LITERAL, ARRAY_LITERAL, REGEX_LITERAL,
    // TYPES
    NUMBER, STRING, ARRAY,

    // Newline
    NEWLINE,
    EOF // End of file
}